### PR TITLE
Add hid_flash.exe for windows

### PR DESCRIPTION
**Pull request by BennehBoy**
hid_flash.exe required for HID Bootloader 2.0 support in Arduino_Core_STM32

Windows only at this stage

### CODE REVIEW

**Comment by BennehBoy** [comment]
Hi, its the exe from Roger's core, I'll hunt down the source later. There's also macos and Linux versions

**Comment by fpistm** [comment]
@BennehBoy 
I saw several work on going on the HID BL and probably this tools requires update?
So, I guess it should be fine to wait a stable version ?

**Comment by BennehBoy** [comment]
@fpistm there's not an updated version, there's some hefty debate ongoing about whether to issue a high memory F1 version of the bootloader.  For now I think this is safe to add, but I guess there's no point until the hid/dfu PR get's merged.

**Comment by fpistm** [comment]
Hi @BennehBoy,
I close this PR as @Serasidis provided an updated version of the `hid-flash` thanks #36.

**Comment by BennehBoy** [comment]
NP

**Pull request closed without merging**
