### PR TITLE
STM32CubeProg.sh(Erase memory when using DFU)

### PR DESCRIPTION
**Pull request by narzul**
Programming problems when using DFU.
* When programming with DFU, unable to write non-zero data to already programmed memory.
* Resulting in memory map error, validation error and incorrect data.

Added
* Added: ERASE="yes"
* When DFU is selected

### CODE REVIEW

**Comment by fpistm** [comment]
Hi @narzul 
It seems more a workaround than a real solution.
Erasing the whole flash each time will reduce life of the flash cycle.
Which board you used?

**Comment by narzul** [comment]
Greetings @fpistm 
The board that I'm currently working on is the adafruit stm32f405.
However this is a persistent problem for all stm32f4xx chips when programming using DFU.
It is also a general problem for many other stm32 chips, when programming using DFU.

But if you think that this is something that should be addressed a different place, would you be able to point me in the right direction, so I can write a fix there.

**Comment by fpistm** [comment]
I have the Adafruit F405 and never had this issue same for other series. Which version of cubeprogrammer you used?

**Comment by narzul** [comment]
I'm running STM32CubeProgrammer v2.16.0

**Comment by fpistm** [comment]
Hi @narzul 
Since the script was reworked, see https://github.com/stm32duino/Arduino_Core_STM32/pull/2323 and #97 .

The simpliest way is to use the [`boards.local.txt`](https://arduino.github.io/arduino-cli/0.29/platform-specification/#boardslocaltxt)

```
# Add erase option to dfu upload method, --erase could also be used
GenF4.menu.upload_method.dfuMethod.upload.options=-v {upload.vid} -p {upload.pid} -e
```

**Pull request closed without merging**
