### PR TITLE
Fix permission and issue with x86_64 host

### PR DESCRIPTION
**Pull request by fpistm**
Hi,

this patch add exec permission for nucleoFlasher on Linux.
Moreover, it allows to use stlink on a 64bits distribution as Arduino IDE do not deal it properly.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
OK.

I didn't realise that there were still some permissions problems.

I had a similar problem when I commited OSX and Linux tools via my PC and I lost the permissions, so I had to recommit via my Mac to fix the permissions

Re: Linux64 support.

Yes. Thats a good idea. I need to do something similar on my LibMaple based repo, as the linux tools do not automatically run the correct version, and not all Linux64 systems will run the Linux32 bit binaries

**Comment by fpistm** [comment]
Hi Roger,
In fact Linux 64 could run the 32 one if the user install the libusb-1.0-0:i386 (ex for my Ubuntu 14.04) but it is more simple to do like that. Nonetheless, it should be better than Arduino IDE deal with it properly ☺

Best regards

[Description: Description: Description: Description: Description: Description: Description: Description: Description: Description: Description: Description: Description: logo_big5]

Frédéric PILLON | Tel: +33 244027381
STMicroelectronics | MDG | Embedded Software
ST online: www.st.com<http://www.st.com/> | Follow us on twitter: @st_world<http://twitter.com/#!/ST_World>
P Please consider the environment before printing this e-mail.

**Comment by rogerclarkmelbourne** [comment]
Hi Frederic

Yes. Linux 64 and sometimes run 32 bit, but we found there are many different Linux distro’s and some had problems.

I agree it would be best if the Arduino IDE could do this automatically, but your script is a good solution and I will also use it for the LibMaple repo is that is OK?

Thanks

Roger

**Comment by fpistm** [comment]
Yes of course it is ok.

Best regards

[Description: Description: Description: Description: Description: Description: Description: Description: Description: Description: Description: Description: Description: logo_big5]

Frédéric PILLON | Tel: +33 244027381
STMicroelectronics | MDG | Embedded Software
ST online: www.st.com<http://www.st.com/> | Follow us on twitter: @st_world<http://twitter.com/#!/ST_World>
P Please consider the environment before printing this e-mail.

**Pull request merged**
