### PR TITLE
[linux] Create dfu-util script to select correct program (32/64-bit)

### PR DESCRIPTION
**Pull request by jgillick**
In order to support dfu-util as a first-class upload option in linux, there needs to be a script that will choose the correct compiled program (x86_64/i386). This PR was inspired by this [PR comment](https://github.com/stm32duino/Arduino_Core_STM32/pull/709#discussion_r336329735).

**Why**
Since dfu-util is already bundled when installing the STM32 core, this PR removes any outside software dependency necessary for the end-user. Additionally, the STM32CubeProgrammer installer [is known](https://community.st.com/s/question/0D50X00009cdVnZSAU/stm32cubeprogrammer-fails-to-install-in-macos) to have issues on the mac -- there are workarounds, but it's one more hurdle for the end-user to jump through.

**Directory Change**
Part of this PR is to rename the `dfu-util` directory to `dfu-util_i386` so the main script could be called `dfu-util` in the linux directory. (this makes the `platform.txt` config more straight forward) I'm not sure if this changes any kind of build step necessary for the releases.

**Related Issue**
While testing this PR, I noticed a [related issue](https://github.com/stm32duino/Arduino_Tools/issues/45). It seems like the i386 compiled binary is actually compiled for x86_64 systems. ~That issue can be ignored if this is expected.~ 
_I have updated the i386 binaries from the [official distribution](http://dfu-util.sourceforge.net/releases/) and tested them on a virtualized 32-bit system._

### CODE REVIEW

**Comment by fpistm** [comment]
This is not really needed to rename the dfu-util directory.
Main issue is t provide a 32bits version of the binaries.

**Comment by jgillick** [comment]
I'm not really sure I understand your comment on this PR. From  [this comment](https://github.com/stm32duino/Arduino_Core_STM32/pull/709#discussion_r336329735) on my other PR, don't we need to create a script to call the correct binary? Since all other OSes will look for a `dfu-util` program, it would make sense to name this script the same.

**Comment by jgillick** [comment]
The binaries have been updated to work for 32-bit systems in this PR as well.

**Comment by jgillick** [comment]
I have reversed the directory name change and name the chooser script `dfu-util.sh`. (it'll proxy the command to the correct binary)

**Comment by fpistm** [comment]
Fixes #45

**Pull request merged**
